= Drubone - universal solution for Drupal to manage configuration for multi-site and single-site docroot setups

== Features from the box:

* Drush aliases generator for multi-site (and single-site) setups based on /sites directory using standard schema (_you only need to configure servers IPs / SSH user / path to docroot on server to make local & remote aliases work for every site in setup, e.g. you can have @local.site1.en, @local.site1.fr, @dev.site1.en, @dev.site1.fr, @prod.site1.en, @prod.site1.fr aliases without the need to configure each site separately_);

* Multisite setup configuration in YAML format instead of lacking extended configuration capabilities default sites.php file, allowing to provide andy additional settings for each site/URL;

* Customisable and manageable environment-specific (and any other custom specific parameters possible) settings files (_environment indicators, standard caching settings, etc_) in both YAML & PHP formats;

* Drubone is highly configurable, so you can setup it in any specific way that will suit demands of your project or you can just use it from the box;

* Works for both Drupal 7 & 8;

* Some examples of using Drubone:

** You can have URL-specific settings file (in PHP format) that will be included for specific URLs only (useful if you need specific settings for some of the pages/subdomains/domains) OR:

** You can add URL-specific settings in YAML configuration file;

** You can override any of the Drupal settings in YAML format in single file for every site in setup, or for every site in specific environment or use any other combination of server, environment, instance, etc;

